dssync:
   path: /opt/srlinux/dssync/bin/
   launch-command: ./dssync
   search-command: ./dssync
   wait-for-config: Yes
   start-order: 254
   failure-threshold: 100
   failure-action: "wait=60"
   yang-modules:
       names: 
           - "dssync"
       source-directories:
           - "/opt/srlinux/dssync/yang/"
